cli.php, includes/class-gf-cli-form.php, readme.txt
re: [HS#217740](https://secure.helpscout.net/conversation/558980046/217740?folderId=5488)
Fix an issue where the id of the form to be updated is not being used to get the form. 
The `$form` is run through `absint` by `GFAPI::get_form` which results in the form id of 1 being used to retrieve the form. 
If a form with the id 1 does not exist the form update command returns the `Form not found` error.
If a form with the id 1 does exist `GFAPI::update_form` updates the correct form (not id 1) as it gets the id of the form to be updated from the `$form['id']`.
=> Fix form update

cli.php, includes/class-gf-cli-form-field.php, readme.txt
When using `--field-json` the field updated but also returned a warning with the success message.
>Warning: The \`wp gf form field update\` command has an invalid synopsis part: `[--<field-property>=<field-value>]`
Using `wp gf form field update 14 2 --visibility=visible` returned a parameter error: 
> unknown --visibility parameter
Changing `[--<field-property>=<field-value>]` to `[--<property>=<value>]` resolved both issues.
=> Fix field update property parameter

cli.php, includes/class-gf-cli-license.php, readme.txt
re: [HS#217464](https://secure.helpscout.net/conversation/557418314/217464/?folderId=5488)
Fixes the unlicensed copy notice remaining after updating the license key.
=> Fix remote message remaining after key change

includes/class-gf-cli-root.php, readme.txt
This PR fixes an error message displayed when Gravity Forms is installed using the "wp gf install" command. Since Gravity Forms 2.3 the set up is now handled automatically on plugin activation.
Addresses [HS232385](https://secure.helpscout.net/conversation/660711788/232385?folderId=29193)
**Testing instructions**
On master, use the `wp gf install --key=xxxxx --activate` command to install Gravity Forms. Notice the "Error: Use the --force flag to force the database setup." message. Check with this branch that the error message is not displayed but the installation and set up is complete.
=> Fix error message on gf install

includes/class-gf-cli-entry.php
This PR adds support for specifying a start_date and end_date when exporting entries using the `wp gf entry export` command.
Addresses [HS237383](https://secure.helpscout.net/conversation/702342190/237383/?folderId=5492) and PR  #12 
**Testing instructions**
Test that the start and end dates are respected when exporting to both JSON and CSV formats. e.g. 
```
wp gf entry export 11 --start_date="2018-11-01" --end_date="2018-11-11" --format=json
wp gf entry export 11 --end_date="2018-11-11" --format=csv
wp gf entry export 11 --start_date="2018-11-11" --format=json
```
=> Add entry export dates

includes/class-gf-cli-form.php
This PR adds IDs to fields if the ID is missing when creating a form using the `wp gf form create` command. Missing field IDs generate errors in the form editor and display.
Addresses issue #11
**Testing instructions**
To reproduce the issue on master create a form with the following command. Notice the fields are missing IDs.
`wp gf form create --form-json='{ "title": "test", "description": "", "labelPlacement": "top_label", "descriptionPlacement": "below", "button": { "type": "text", "text": "Submit", "imageUrl": "" }, "fields": [ { "type": "text", "label": "Untitled", "adminLabel": "", "isRequired": false, "size": "medium", "errorMessage": "", "visibility": "visible", "inputs": null, "formId": 1, "description": "", "allowsPrepopulate": false, "inputMask": false, "inputMaskValue": "", …
=> Fix missing field IDs when creating a form

includes/class-gf-cli-form-field.php
This PR fixes an issue with the `wp gf field update` command where arbitrary properties/value pairs are not accepted by the command.
Fixes [HS236084](https://secure.helpscout.net/conversation/691307996/236084/?folderId=29193)
**Testing instructions**
To reproduce the issue on master use the `wp gf field update` command to update a field property. E.g.
`wp gf field update 18 1 --label="test2"`
The following error will be displayed and the command will not be run:
```
Warning: The `wp gf field update` command has an invalid synopsis part: [--<property>=<value>]
Error: Parameter errors:
unknown --label parameter
```
On this branch the update will be successful:
`Success: Field ID: 1 updated`
=> Fix field property updates

README.md, cli.php, includes/class-gf-cli-entry.php
RE: [HS #263011](https://secure.helpscout.net/conversation/910586289/263011?folderId=2752516)
Currently when exporting entries to a CSV via the CLI add-on the status will be listed as "Exporting 0 entries" regardless of the amount of entries a form has. This branch fixes an issue where the entry status was always set to "status" rather than a valid status.
- Create a form and submit it a few times to create entires. You could also use an existing form that has entires.
- Run the following command subbing FORMID for your form's ID:
`wp gf entry export FORMID`
- Notice that despite the number of entries present on the form, "Exporting 0 entries" will be output next to the progress bar while exporting entries.
- Check the contents of the CSV file created, notice the correct data and amount …
=> Fix entry export status

includes/class-gf-cli-entry.php
Allow paging for ids format too.
`GFFormsModel::search_lead_ids()` is a wrapper for `GFAPI::get_entry_ids()` with less parameters.
=> entry list: same features for json as ids format

includes/class-gf-cli-form.php
I had support put this in as a feature request, but I ended up needing to make the local plugin edit myself anyway, so I figured I'd contribute what I used. Feel free to edit/merge if you please.
=> adds optional filename flag for form export

includes/class-gf-cli-form-notification.php
Supersedes #20 and #24 
Fixes a notice which occurs when using the command without including the `<notification-id>` arg.
```
[18-Nov-2019 10:50:42 UTC] PHP Notice:  Undefined offset: 1 in /app/public/wp-content/plugins/gravityformscli/includes/class-gf-cli-form-notification.php on line 406
[18-Nov-2019 10:50:42 UTC] PHP Stack trace:
[18-Nov-2019 10:50:42 UTC] PHP   1. {main}() /usr/local/bin/wp:0
[18-Nov-2019 10:50:42 UTC] PHP   2. include() /usr/local/bin/wp:4
[18-Nov-2019 10:50:42 UTC] PHP   3. include() phar:///usr/local/bin/wp/php/boot-phar.php:11
[18-Nov-2019 10:50:42 UTC] PHP   4. WP_CLI\bootstrap() phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php:27
[18-Nov-2019 10:50:42 UTC] PHP   5. WP_CLI\Bootstrap\LaunchRunner->process() …
```
=> Fix the notification-id arg for the form notification update command

cli.php, includes/class-gf-cli-root.php, readme.txt
RE: [HS #288035](https://secure.helpscout.net/conversation/1095496963/288035?folderId=2752516)
The wp gf install command does not use the correct WP CLI flag for network activating plugins on install. Currently we are using --network-activate [when the flag is actually --activate-network](https://developer.wordpress.org/cli/commands/plugin/install/), this leads to receiving the following error when used:
`Error: Parameter errors:
unknown --network-activate parameter`
This PR updates the install command to use the correct flag.
- Spin up a WP Multisite install and install WP CLI (if necessary, pre-installed on Local) and the CLI add-on by cloning the repo into your new installs plugins directory.
- Run the following command subbing XXXX for your GF license key:
`wp gf install --key=XXXX …
=> Fix network activate install flag

cli.php, includes/class-gf-cli-root.php, readme.txt
This PR updates Gravity API URL to use the `www.gravityapi.com` domain.
1. Activate the Gravity Forms Cli plugin. If you use Local by Flywheel, it already has WPCli installed, or you'll have to install WPCli on your server.
2. Add `define( 'GRAVITY_MANAGER_URL', 'https://dev.gravityhelp.com/wp-content/plugins/gravitymanager' );` to your `wp-config.php` file.
3. In the Local app, right-click on your site and click on "Open Site SSH" (https://d.pr/i/NK3RLO). Or ssh to your server.
4. Run the command `wp gf check_update` to see if you can get results.
5. Update the constant in `wp-config.php` to `https://dev.gravityapi.com/wp-content/plugins/gravitymanager`.
6. Repeat step 4.
=> Update Gravity API domain

includes/class-gf-cli-form-notification.php
re: [HS#303986](https://secure.helpscout.net/conversation/1225740721/303986)
This fixes some issues with the docblock for the notification create command, the main being that the synopsis is for a different command so using the `--notification-json` option resulted in a parameter error.
Once the synopsis was fixed I noticed that the form id was assigned as the notification name instead of the value provided for the `name` option. This was fixed by getting the value from `$args[1]` instead of `$args[0]`.
- With master enter `wp gf form notification create 1 'the name' --notification-json='{"subject":"the subject","message":"the message","from":"{admin_email}","fromName":"the from name"}'` replacing `1` with the ID of your test form
- Find a parameter error occurs
- Switch to this branch
- …
=> Fix notification create command

change_log.txt, cli.php, includes/class-gf-cli-root.php, readme.txt
Closes #29 
This adds support for installing or updating to Gravity Forms beta releases. We are not supporting add-on betas with this release.
- On a site with 2.4 run `wp gf update --version=beta`
- Find the beta is installed
- Run `wp plugin delete gravityforms`
- Run `wp gf install --version=beta --key=your_key_here`
- Find the beta is installed
- Run `wp gf install gravityformszapier --version=beta --key=your_key_here`
- Find the `--version=beta is not currently supported by add-ons.` error is output
- Run `wp gf install gravityforms-beta --key=your_key_here`
- Find the `Appending -beta to the slug is not supported. Use --version=beta instead.` error is output
=> Update the install and update commands to support beta releases

change_log.txt, includes/class-gf-cli-root.php, readme.txt
This fixes a fatal error which occurs when Gravity Forms is not active and the version command is used with an add-on slug
- Run `wp plugin deactivate gravityforms`
- Run `wp gf version gravityformsstripe`
- Find the `There has been a critical error on your website.Learn more about debugging in WordPress. There has been a critical error on your website.` error is output and there is a fatal error in the debug.log file
- Switch to this branch
- Repeat command to find the fatal error does not occur and the `Gravity Forms is not installed. Use the wp gf install command.` error is output
=> Fix fatal error which can occur when using the version command with an add-on slug

change_log.txt, cli.php, includes/class-gf-cli-root.php, readme.txt
This fixes an issue where the Gravity Forms version number is used instead of the add-on version number when the update command checks if the plugin has already been updated.
`GF_CLI_Root::get_addon()` has been added to get the current instance of the add-on for the given slug.
- Edit the version number in advancedpostcreation.php so it is older than the latest build e.g. 1.0-beta-4
- Run `wp gf update gravityformsadvancedpostcreation`
- Find the `Plugin already updated` success message is output
- Note this is incorrect as the latest version is 1.0-beta-5
- Switch to this branch
- Repeat command
- Find the latest version of the add-on is downloaded and installed
- Run `wp gf version gravityformsadvancedpostcreation` to confirm the correct version is output
- Run `wp plugin deactivate …
=> Fix update command using GF version for add-on slugs

composer.json
This PR fixes gravityforms/backlog#386 by updating the package type to wordpress-plugin
1. Outside of your WordPress installation, in another directory, create a `composer.json` file with the following contents:
```
{
"repositories": [
{
"type": "git",
"url": "git@github.com:gravityforms/gravityformscli.git"
}
],
"require": {
"composer/installers": "^1.11",
"gravityforms/gravityformscli": "^1.4"
}
}
```
2. Run `composer install`.
3. Review the contents of the directory. You should see a `composer.lock` file and a `vendor` directory. The vendor directory should contain a directory named `gravityforms`, which itself contains a directory named `gravityformscli`, which contains the contents of this repository.
4. Run `rm --rf vendor composer.lock` in the command line.
5. Run `composer require …
=> Update type to wordpress-plugin

change_log.txt, class-gf-cli.php, cli.php, composer.json, includes/class-gf-cli-entry-notification.php, includes/class-gf-cli-entry.php, includes/class-gf-cli-form-field.php, includes/class-gf-cli-form-notification.php, includes/class-gf-cli-form.php, includes/class-gf-cli-license.php, includes/class-gf-cli-root.php, includes/class-gf-cli-tool.php, readme.txt
This PR adds the ability to use the plugin as a global WP-CLI Package, to make all GF CLI commands available to any site installed on the server without the need of installing the plugin on each site.
Closes https://github.com/gravityforms/backlog/issues/3983
Closes https://github.com/gravityforms/backlog/issues/3039 by updating the "Tested up to" version
1. Download this branch as a ZIP file from Github, not the package built with HAL because it removes the `composer.json` file.
2. Using the command line, install the plugin as a global WP-CLI Package with this command: `wp package install <full path to the zip file>`
a. What location should I be at? installed from within local/site/app/public (site didn't have gravityforms repo) and it installed to …
=> Allow usage as wp cli package

change_log.txt, cli.php, includes/class-gf-cli-root.php
This change updates our CLI tool to work for updating GravitySMTP. At this time, we just hardcoded a check for SMTP specifically, but as more new products come out we're going to want to look into updating this to be more general-purpose.
Addresses: https://github.com/gravityforms/backlog/issues/5337
- Start a fresh site and install/enable this plugin
- Use `wp gf install gravityforms --key={your_key}` and `wp gf install gravitysmtp --key={your_key}` to install both plugins
- Go to the Plugins page and enable each plugin
- Manually edit the version in `gravitysmtp.php` to be a lower version
- Run `wp gf update gravitysmtp --key={your_key}`
- Ensure that the update works correctly and your plugin is fully updated
=> Adds GravitySMTP Support to Update Command
